### PR TITLE
introduce a more prod ready helm chart for lago

### PR DESCRIPTION
**Pull request by grafjo**
* use helm apiVersion v2
* having separated template folders for each deployment
* adjust all templates to use most of options when generating a new chart via `helm create`
* add github action to publish chart via gh pages
* add minio as optional chart dependency
* add some examples - see charts/lago/examples.md
* allow to use existing secrets
* introduce dedicated ingress objects for front and api
* introduce init-contains to check if db is available / schema exists
* add health checks whenever possible
* make events worker optional

### CODE REVIEW

**Comment by jdenquin** [comment]
Hello @grafjo 

Thanks a lot for this PR, I know that we already have some users in production with the actual version of the chart, could we keep the `values.yaml` format and improve the deployments/service only? It will avoid a breaking change for them

**Comment by grafjo** [comment]
Hey @jdenquin

I'm aware that this change is one big breaking change (or a lot of small ones :-)).

How can we deal with possible breaking changes in the future? Somehow they will pop up and some users that are using the released version of this chart have to do some migrations.

If we stick to the current values.yaml attributes / schema, even adopting the improvement of new labels used via deployment and service following [helm standard labels](https://helm.sh/docs/chart_best_practices/labels/#standard-labels) is a breaking change on k8s side.

Maybe we can have a chat about that somewhere else e.g. lago slack?

**Comment by jdenquin** [comment]
yes feel free to send me a message on Slack, or open a thread on `#contributions`

**Comment by jdenquin** [comment]
@grafjo I'm working on the v1 version and I'll take some of your changes!

**Comment by electrosenpai** [comment]
Hi [@grafjo](https://github.com/grafjo),

Thank you so much for your PR and all the awesome features you’ve suggested! 🙏 While we love your ideas, we’re currently focused on avoiding breaking changes as some users still pull directly from the repo. We've created a separate PR that incorporates some of your proposals, while maintaining backward compatibility.

We really appreciate your contribution and look forward to more collaborations in the future!

**Pull request closed without merging**
